services:
  - type: web
    name: cohere-event-scraper
    env: docker
    region: oregon  # Choose your preferred region
    plan: starter  # Free tier
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: LOG_LEVEL
        value: info
      - key: ALLOWED_ORIGINS
        value: "*"  # Update this with your frontend domain in production
      - key: RELOAD
        value: false
      - key: DEBUG
        value: false
      - key: PLAYWRIGHT_TIMEOUT
        value: 60000
      - key: MAX_CONTENT_LENGTH
        value: 10485760
      - key: GEMINI_API_KEY
        sync: false  # This will be set manually through the Render dashboard
      - key: RATE_LIMIT
        value: 100
      - key: RATE_WINDOW
        value: 60
      - key: API_KEY_HEADER
        value: X-API-Key
      - key: SECURE_HEADERS
        value: true 