name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black isort mypy
      
      - name: Lint with flake8
        run: flake8 app tests
      
      - name: Check formatting with black
        run: black --check app tests
      
      - name: Check imports with isort
        run: isort --check-only --profile black app tests
      
      - name: Type check with mypy
        run: mypy app

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
      
      - name: Install Playwright
        run: |
          pip install playwright
          playwright install chromium
      
      - name: Test with pytest
        run: pytest --cov=app
      
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: cohere-event-scraper:test
      
      - name: Test Docker image
        run: |
          docker run --name test-container -d -p 8000:8000 cohere-event-scraper:test
          sleep 5
          curl --fail http://localhost:8000/health || exit 1 